version: "3"
services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  neo4j:
    image: "neo4j:latest"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
